#pragma once

#define MAPPED_KERNEL_START 0x400000
// Text video memory (Non VESA)
#define TEXT_VIDEO_MEMORY (char*)0xB8000

#define VGA_WIDTH 80
#define VGA_HEIGHT 25
#define BYTES_PER_CHAR 2

#define NUM_MANY_DIRECTORIES 4

#define PAGE_SIZE 4096
#define UPPER_KERNEL_MEMORY_START 0xC0000000

#define ALIGN_DOWN(x, y) ((x) & ~((y) - 1))
#define ALIGN_UP(x, y) (((x) + ((y) - 1)) & ~((y) - 1))

#define PHYSICAL_KERNEL_STACK_TOP 0x90000
#define UPPER_KERNEL_STACK_TOP 0xC03FFFFF
#define KERNEL_STACK_SIZE (64 * 0x1000) // 64 kB stack size
#define UPPER_KERNEL_STACK_BASE (UPPER_KERNEL_STACK_TOP - KERNEL_STACK_SIZE)

#define HEAP_SIZE 0x400000
#define KERNEL_HEAP_SIZE 0x20000000

#define HEAP_VIRT_START 0xC0400000
#define HEAP_VIRT_END (HEAP_VIRT_START + HEAP_SIZE)
#define KERNEL_HEAP_VIRT_START (HEAP_VIRT_START + HEAP_SIZE)
#define KERNEL_HEAP_VIRT_END (KERNEL_HEAP_VIRT_START + KERNEL_HEAP_SIZE)

#define HEAP_PAGE_TABLES (ALIGN_UP(HEAP_SIZE, 0x400000) / 0x400000)
#define KERNEL_HEAP_PAGE_TABLES (ALIGN_UP(KERNEL_HEAP_SIZE, 0x400000) / 0x400000)

#define FRAMEBUFFER_VIRT_START 0xAF000000                             // vesa
#define FRAMEBUFFER_PD_INDEX ((FRAMEBUFFER_VIRT_START >> 22) & 0x3FF) // 752
#define FRAMEBUFFER_PT_INDEX ((FRAMEBUFFER_VIRT_START >> 12) & 0x3FF) // 0
#define NUM_FB_PAGE_DIRS 2
#define FRAMEBUFFER_SIZE_BYTES(vres, pitch) ((vres) * (pitch))
#define FRAMEBUFFER_NUM_DIRECTORIES(vres, pitch)                                                   \
	(((FRAMEBUFFER_SIZE_BYTES(vres, pitch) + 0x3FFFFF) / 0x400000))

#define FRAMEBUFFER_VIRT_END(vres, pitch)                                                          \
	(FRAMEBUFFER_VIRT_START + FRAMEBUFFER_SIZE_BYTES(vres, pitch))

#define FRAMEBUFFER_PAGE_DFLAGS (PD_FLAGS)(PD_PRESENT | PD_READWRITE)
#define FRAMEBUFFER_PAGE_TFLAGS (PT_FLAGS)(PT_PRESENT | PT_READWRITE | PT_WRITECOMBINING);